name: 'Build and push the latest version'

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: 'Deploy latest version'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET /repos/codecentric/spring-boot-admin/releases/latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@70e1ff84cbd75a9e03941a79f21f05f1b03a71bb
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@b5730d24715e542a67be9991a420842b8b072900
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: 'latest,${{ step.get_latest_release.outputs.data.tag_name }}'
          labels: ${{ steps.meta.outputs.labels }}
          build-args: SPRING_BOOT_ADMIN_VERSION=${{ step.get_latest_release.outputs.data.tag_name }}
