name: 'Build and push the latest version'

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: 'Deploy latest version'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET /repos/codecentric/spring-boot-admin/releases/latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: "echo latest release: ${{ steps.get_latest_release.outputs }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@70e1ff84cbd75a9e03941a79f21f05f1b03a71bb
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@1237c3e3d6926ae8bfad16f64e08d259b9943637
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@b5730d24715e542a67be9991a420842b8b072900
        with:
          context: .
          push: true
          tags: 'latest,${{ fromJson(steps.get_latest_release.outputs.data).tag_name }}'
          labels: ${{ steps.meta.outputs.labels }}
          build-args: SPRING_BOOT_ADMIN_VERSION=${{ fromJson(steps.get_latest_release.outputs.data).tag_name }}
