name: 'Build and push the latest version'

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: 'Deploy latest version'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET /repos/codecentric/spring-boot-admin/releases/latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: "echo latest release: ${{ steps.get_latest_release.outputs }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@70e1ff84cbd75a9e03941a79f21f05f1b03a71bb
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@b5730d24715e542a67be9991a420842b8b072900
        with:
          context: .
          push: true
          tags: '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ fromJson(steps.get_latest_release.outputs.data).tag_name }}'
          platforms: linux/amd64,linux/arm64
          labels: |
            org.opencontainers.image.licenses=Apache-2.0
            org.opencontainers.image.title=spring-boot-admin-docker
            org.opencontainers.image.description=Prepackaged version of spring-boot, wrapped in a container
            org.opencontainers.image.url=https://github.com/cloudflightio/spring-boot-admin-docker
            org.opencontainers.image.source=https://github.com/cloudflightio/spring-boot-admin-docker
            org.opencontainers.image.version=nightly
          build-args: SPRING_BOOT_ADMIN_VERSION=${{ fromJson(steps.get_latest_release.outputs.data).tag_name }}
